# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/protos/artist.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Artist" do
    optional :name, :string, 1
  end
end

Artist = Google::Protobuf::DescriptorPool.generated_pool.lookup("Artist").msgclass
