# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/protos/contributor_roles.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ContributorRole" do
    optional :role, :enum, 1, "ContributorRole.Role"
  end
  add_enum "ContributorRole.Role" do
    value :ARTWORK, 0
    value :PHOTOGRAPHY, 1
    value :EXECUTIVE_PRODUCER, 2
    value :OTHER, 3
    value :WRITTEN_BY, 4
    value :PUBLISHER, 5
  end
end

ContributorRole = Google::Protobuf::DescriptorPool.generated_pool.lookup("ContributorRole").msgclass
ContributorRole::Role = Google::Protobuf::DescriptorPool.generated_pool.lookup("ContributorRole.Role").enummodule
