# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Product.Metadata" do
  end
end

module Product
  Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("Product.Metadata").msgclass
end
