# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recording.proto

require 'google/protobuf'

require_relative 'artist_pb'
require_relative 'contributor_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Recording" do
    optional :uuid, :string, 1
    optional :title, :string, 2
    optional :identification_number, :enum, 3, "Recording.IdentificationNumber"
    repeated :artists, :message, 4, "Artist"
    repeated :contributors, :message, 5, "Contributor"
  end
  add_enum "Recording.IdentificationNumber" do
    value :ISRC, 0
    value :ISWC, 1
  end
end

Recording = Google::Protobuf::DescriptorPool.generated_pool.lookup("Recording").msgclass
Recording::IdentificationNumber = Google::Protobuf::DescriptorPool.generated_pool.lookup("Recording.IdentificationNumber").enummodule
