# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: release.proto

require 'google/protobuf'

require_relative 'artist_pb'
require_relative 'contributor_pb'
require_relative 'recording_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Release" do
    optional :uuid, :string, 1
    optional :title, :string, 2
    optional :custom_id, :string, 3
    optional :grid, :string, 4
    optional :copyright_year, :int32, 5
    optional :catalogue_number, :string, 6
    repeated :artists, :message, 7, "Artist"
    repeated :contributors, :message, 8, "Contributor"
    repeated :recordings, :message, 9, "Recording"
  end
end

Release = Google::Protobuf::DescriptorPool.generated_pool.lookup("Release").msgclass
