#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Release
  # forward declarations
  class Metadata < ::ProtocolBuffers::Message; end
  class Artist < ::ProtocolBuffers::Message; end
  class Contributor < ::ProtocolBuffers::Message; end
  class Label < ::ProtocolBuffers::Message; end

  class Metadata < ::ProtocolBuffers::Message
    set_fully_qualified_name "Release.Metadata"

    required :string, :title, 1
    required :string, :uuid, 2
    optional :string, :grid, 3
    required :string, :catalogue_number, 4
    required :string, :release_date, 5
  end

  class Artist < ::ProtocolBuffers::Message
    set_fully_qualified_name "Release.Artist"

    required :string, :name, 1
  end

  class Contributor < ::ProtocolBuffers::Message
    set_fully_qualified_name "Release.Contributor"

    required :string, :name, 1
  end

  class Label < ::ProtocolBuffers::Message
    set_fully_qualified_name "Release.Label"

    required :string, :name, 1
  end

end
