# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: release.proto

require 'google/protobuf'

require 'artist_pb'
require 'contributor_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Release.Metadata" do
    optional :uuid, :string, 1
    optional :title, :string, 2
    optional :custom_id, :string, 3
    optional :grid, :string, 4
    optional :copyright_year, :int32, 5
    optional :catalogue_number, :string, 6
    repeated :artists, :message, 7, "Artist"
  end
  add_message "Release.Label" do
    optional :name, :string, 1
  end
end

module Release
  Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("Release.Metadata").msgclass
  Label = Google::Protobuf::DescriptorPool.generated_pool.lookup("Release.Label").msgclass
end
