# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artist.proto

require 'google/protobuf'

require_relative 'registration_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Artist" do
    optional :sequence, :int32, 1
    optional :name, :string, 2
    repeated :registrations, :message, 3, "Registration"
  end
end

Artist = Google::Protobuf::DescriptorPool.generated_pool.lookup("Artist").msgclass
