# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attached_file.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "AttachedFile" do
    optional :file_name, :string, 1
    optional :file_size, :int32, 2
    optional :file_extension, :string, 3
    optional :file_location, :string, 4
  end
end

AttachedFile = Google::Protobuf::DescriptorPool.generated_pool.lookup("AttachedFile").msgclass
