# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_genre.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("base_genre.proto", :syntax => :proto3) do
    add_message "mscm.BaseGenre" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :name, :enum, 2, "mscm.BaseGenre.Name"
    end
    add_enum "mscm.BaseGenre.Name" do
      value :NAME_UNSPECIFIED, 0
      value :NAME_ALTERNATIVE, 1
      value :NAME_AUDIO_BOOKS, 2
      value :NAME_BLUES, 3
      value :NAME_CHILDRENS_MUSIC, 4
      value :NAME_CLASSICAL, 5
      value :NAME_COMEDY, 6
      value :NAME_COUNTRY, 7
      value :NAME_DANCE, 8
      value :NAME_ELECTRONIC, 9
      value :NAME_FOLK, 10
      value :NAME_HIPHOP_RAP, 11
      value :NAME_HOLIDAY_MUSIC, 12
      value :NAME_INSPIRATIONAL, 13
      value :NAME_JAZZ, 14
      value :NAME_LATIN, 15
      value :NAME_NEW_AGE, 16
      value :NAME_OPERA, 17
      value :NAME_POP, 18
      value :NAME_RB_SOUL, 19
      value :NAME_REGGAE, 20
      value :NAME_ROCK, 21
      value :NAME_SOUNDTRACK, 22
      value :NAME_SPOKEN_WORD, 23
      value :NAME_VOCAL, 24
      value :NAME_WORLD, 25
    end
  end
end

module Mscm
  BaseGenre = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.BaseGenre").msgclass
  BaseGenre::Name = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.BaseGenre.Name").enummodule
end
