# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: company.proto

require 'google/protobuf'

require 'profile_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("company.proto", :syntax => :proto3) do
    add_message "mscmetadata.Company" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :tmn_id, :string, 2
      optional :name, :string, 3
      optional :profile, :message, 4, "mscmetadata.Profile"
    end
  end
end

module Mscmetadata
  Company = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Company").msgclass
end
