# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contributor.proto

require 'google/protobuf'

require_relative 'contributor_roles_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Contributor" do
    optional :name, :string, 1
    optional :contributor_roles, :message, 2, "ContributorRole"
  end
end

Contributor = Google::Protobuf::DescriptorPool.generated_pool.lookup("Contributor").msgclass
