# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contributor.proto

require 'google/protobuf'

require 'profile_pb'
require 'registration_pb'
require 'url_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("contributor.proto", :syntax => :proto3) do
    add_message "mscmetadata.Contributor" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :name, :string, 2
      optional :profile, :message, 3, "mscmetadata.Profile"
      repeated :registrations, :message, 4, "mscmetadata.Registration"
      repeated :urls, :message, 5, "mscmetadata.URL"
    end
  end
end

module Mscmetadata
  Contributor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Contributor").msgclass
end
