# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contributor_role.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("contributor_role.proto", :syntax => :proto3) do
    add_message "mscmetadata.ContributorRole" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :role, :enum, 2, "mscmetadata.ContributorRole.Role"
    end
    add_enum "mscmetadata.ContributorRole.Role" do
      value :ARTWORK, 0
      value :PHOTOGRAPHY, 1
      value :EXECUTIVE_PRODUCER, 2
      value :OTHER, 3
      value :WRITTEN_BY, 4
      value :PUBLISHER, 5
    end
  end
end

module Mscmetadata
  ContributorRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.ContributorRole").msgclass
  ContributorRole::Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.ContributorRole.Role").enummodule
end
