# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delivery.proto

require 'google/protobuf'

require 'attachment_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("delivery.proto", :syntax => :proto3) do
    add_message "mscm.Delivery" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :delivery_id, :string, 2
      optional :attachments, :message, 3, "mscm.Attachment"
      optional :type, :enum, 4, "mscm.Delivery.Type"
    end
    add_enum "mscm.Delivery.Type" do
      value :TYPE_RELEASE_UNSPECIFIED, 0
      value :TYPE_RECORDING, 1
      value :TYPE_RINGTONE, 2
      value :TYPE_MOVIE, 3
    end
  end
end

module Mscm
  Delivery = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.Delivery").msgclass
  Delivery::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.Delivery.Type").enummodule
end
