# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("file.proto", :syntax => :proto3) do
    add_message "mscmetadata.File" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :name, :string, 2
      optional :size, :int32, 3
      optional :extension, :string, 4
      optional :mime_type, :string, 5
      optional :created_at, :string, 6
      optional :location, :string, 7
      optional :notes, :string, 8
    end
  end
end

module Mscmetadata
  File = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.File").msgclass
end
