# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genre.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Genre" do
    optional :name, :string, 1
  end
end

Genre = Google::Protobuf::DescriptorPool.generated_pool.lookup("Genre").msgclass
