# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identifier.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("identifier.proto", :syntax => :proto3) do
    add_message "mscm.Identifier" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :name, :string, 2
      optional :reference, :string, 3
    end
  end
end

module Mscm
  Identifier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.Identifier").msgclass
end
