# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label.proto

require 'google/protobuf'

require 'profile_pb'
require 'url_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("label.proto", :syntax => :proto3) do
    add_message "mscm.Label" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :tmn_id, :string, 2
      optional :name, :string, 3
      optional :profile, :message, 4, "mscm.Profile"
      repeated :urls, :message, 5, "mscm.URL"
    end
  end
end

module Mscm
  Label = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.Label").msgclass
end
