# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("language.proto", :syntax => :proto3) do
    add_message "mscmetadata.Language" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :family, :string, 2
      optional :name, :string, 3
      optional :native_name, :string, 4
      optional :iso_alpha_two, :string, 5
      optional :iso_alpha_three, :string, 6
      optional :english_iso_alpha_three, :string, 7
      optional :macro_iso_alpha_three, :string, 8
      optional :notes, :string, 9
    end
  end
end

module Mscmetadata
  Language = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Language").msgclass
end
