# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: performer.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("performer.proto", :syntax => :proto3) do
    add_message "mscmetadata.Performer" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
    end
  end
end

module Mscmetadata
  Performer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Performer").msgclass
end
