# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto

require 'google/protobuf'

require 'url_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("profile.proto", :syntax => :proto3) do
    add_message "mscmetadata.Profile" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :email, :string, 2
      optional :alternative_email, :string, 3
      repeated :urls, :message, 4, "mscmetadata.URL"
    end
  end
end

module Mscmetadata
  Profile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Profile").msgclass
end
