# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recipient.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("recipient.proto", :syntax => :proto3) do
    add_message "mscm.Recipient" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :name, :string, 2
      optional :mscmid, :string, 3
    end
  end
end

module Mscm
  Recipient = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.Recipient").msgclass
end
