# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recording_contributor.proto

require 'google/protobuf'

require 'uuid_pb'
require 'recording_pb'
require 'contributor_pb'
require 'contributor_role_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("recording_contributor.proto", :syntax => :proto3) do
    add_message "mscm.RecordingContributor" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :recording, :message, 2, "mscm.Recording"
      optional :contributor, :message, 3, "mscm.Contributor"
      optional :contributor_role, :message, 4, "mscm.ContributorRole"
    end
  end
end

module Mscm
  RecordingContributor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.RecordingContributor").msgclass
end
