# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Registration" do
    optional :organisation, :string, 1
    optional :code, :string, 2
  end
end

Registration = Google::Protobuf::DescriptorPool.generated_pool.lookup("Registration").msgclass
