# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("registration.proto", :syntax => :proto3) do
    add_message "mscm.Registration" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :organisation, :string, 2
      optional :code, :string, 3
    end
  end
end

module Mscm
  Registration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.Registration").msgclass
end
