# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: release.proto

require 'google/protobuf'

require 'artist_pb'
require 'contributor_pb'
require 'file_pb'
require 'recording_pb'
require 'release_identifier_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("release.proto", :syntax => :proto3) do
    add_message "mscmetadata.Release" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      repeated :files, :message, 2, "mscmetadata.File"
      repeated :artists, :message, 3, "mscmetadata.Artist"
      optional :title, :string, 4
      optional :catalogue_number, :string, 5
      optional :release_date, :string, 6
      optional :record_label, :string, 7
      repeated :identifiers, :message, 8, "mscmetadata.ReleaseIdentifier"
      optional :genre, :string, 9
      optional :style, :string, 10
      optional :copyright_year, :int32, 11
      optional :c_line, :string, 12
      optional :p_line, :string, 13
      optional :biography, :string, 14
      optional :original_format, :string, 15
      optional :country_of_issue, :string, 16
      repeated :contributors, :message, 17, "mscmetadata.Contributor"
      repeated :recordings, :message, 18, "mscmetadata.Recording"
    end
  end
end

module Mscmetadata
  Release = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Release").msgclass
end
