# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rightsholder.proto

require 'google/protobuf'

require 'profile_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("rightsholder.proto", :syntax => :proto3) do
    add_message "mscmetadata.Rightsholder" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :name, :string, 2
      optional :profile, :message, 3, "mscmetadata.Profile"
    end
  end
end

module Mscmetadata
  Rightsholder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Rightsholder").msgclass
end
