# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: royalty.proto

require 'google/protobuf'

require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("royalty.proto", :syntax => :proto3) do
    add_message "mscmetadata.Royalty" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :pay_period, :string, 2
    end
  end
end

module Mscmetadata
  Royalty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Royalty").msgclass
end
