# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sender.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Sender" do
    optional :name, :string, 1
    optional :sender_uid, :string, 2
  end
end

Sender = Google::Protobuf::DescriptorPool.generated_pool.lookup("Sender").msgclass
