# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: uuid.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("uuid.proto", :syntax => :proto3) do
    add_message "mscm.UUID" do
      optional :value, :string, 1
    end
  end
end

module Mscm
  UUID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.UUID").msgclass
end
