# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: work.proto

require 'google/protobuf'

require 'uuid_pb'
require 'recording_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("work.proto", :syntax => :proto3) do
    add_message "mscm.Work" do
      optional :uuid, :message, 1, "mscm.UUID"
      optional :title, :string, 2
      repeated :recordings, :message, 10, "mscm.Recording"
    end
  end
end

module Mscm
  Work = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscm.Work").msgclass
end
