# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: writer.proto

require 'google/protobuf'

require 'society_pb'
require 'uuid_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("writer.proto", :syntax => :proto3) do
    add_message "mscmetadata.Writer" do
      optional :uuid, :message, 1, "mscmetadata.UUID"
      optional :society, :message, 2, "mscmetadata.Society"
      optional :name, :string, 3
      optional :performing_share, :float, 4
      optional :mechanical_share, :float, 5
      optional :role, :string, 6
      optional :membership_number, :string, 7
    end
  end
end

module Mscmetadata
  Writer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mscmetadata.Writer").msgclass
end
